load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Load OpentTelemetry-CPP dependency
http_archive(
    name = "io_opentelemetry_cpp",
    sha256 = "9fe9b357a144300c4d388ab5ef4940b43b611cca73a733322dd22b9faa97391a",
    strip_prefix = "opentelemetry-cpp-5278e8c03586ee1f690916f3e21eab626914c2e0",
    urls = [
        "https://github.com/open-telemetry/opentelemetry-cpp/archive/5278e8c03586ee1f690916f3e21eab626914c2e0.tar.gz"
    ],
)

# Load OpenTelemetry dependencies after load.
load("@io_opentelemetry_cpp//bazel:repository.bzl", "opentelemetry_cpp_deps")

opentelemetry_cpp_deps()

# Load gRPC dependencies after load.
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

# Load extra gRPC dependencies due to https://github.com/grpc/grpc/issues/20511
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

load("@upb//bazel:repository_defs.bzl", "bazel_version_repository")

bazel_version_repository(name = "upb_bazel_version")
