{
  'targets': [{
    'target_name': 'unit_test',
    'type': 'executable',

    # opentelemetry-cpp is built WITH_ABSEIL, so nostd::variant resolves to
    # absl::variant here too. Must match the SDK library.
    'defines': ['HAVE_ABSEIL', 'OPENTELEMETRY_PROTO_API=__attribute__((visibility("default")))'],

    'include_dirs': [
      '../../include/core/',
      '../../include/util/',
      '$(GTEST_INCLUDE_DIR)',
      '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/include/',
      '$(ANSDK_DIR)/apache-log4cxx/1.8.0/include',
      '$(ANSDK_DIR)/apr/1.7.6/include',
      '$(ANSDK_DIR)/apr-util/1.6.5/include',
      '$(BOOST_INCLUDE)'
    ],

    'sources': [
      'unit_test.cpp',
      'ApiUtils_test.cpp',
      'ScopedSpan_test.cpp',
      'ServerSpan_test.cpp',
      'SdkWrapper_test.cpp',
      'SdkUtils_test.cpp',
      'WSAgent_test.cpp',
      'AgentCore_test.cpp',
      'RequestProcessingEngine_test.cpp',
      'SpanNamer_test.cpp',
      'integration_test.cpp',
    ],


    'conditions': [
      ['OS=="linux"', {

        'cflags': [
          '-Wall -pthread -std=c++17',
        ],

        'libraries': [
          # TODO: Following is the sdk library path of the agent. Replace with the actual library to be tested.
          '$(OTEL_SDK_LIB_DIR)/lib/libopentelemetry_webserver_sdk.so',
          '$(GTEST_LIB_DIR)/libgmock.a',
          '$(GTEST_LIB_DIR)/libgmock_main.a',
          '$(GTEST_LIB_DIR)/libgtest.a',
          '$(GTEST_LIB_DIR)/libgtest_main.a',
          '$(ANSDK_DIR)/apache-log4cxx/1.8.0/lib/liblog4cxx.a',
          '$(ANSDK_DIR)/apr-util/1.6.5/lib/libaprutil-1.a',
          '$(ANSDK_DIR)/apr/1.7.6/lib/libapr-1.a',
          '$(ANSDK_DIR)/expat/2.8.5/lib/libexpat.a',
          # Ubuntu's ld defaults to --as-needed and would drop these .so files, since the
          # static OTLP archives that reference them come later in the link line.
          '-Wl,--no-as-needed',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_common.so',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_resources.so',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_trace.so',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_exporter_ostream_span.so',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_instrumentation_scope.so',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_logs.so',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_metrics.so',
          # Same static-linking closure as src/build.gyp - protobuf builds STATIC via
          # gRPC's vendored build, which forces these OTLP targets static too.
          '-Wl,--start-group',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_otlp_recordable.a',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_otlp_common.a',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_exporter_otlp_grpc.a',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_exporter_otlp_grpc_client.a',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_proto.a',
          '$(ANSDK_DIR)/opentelemetry/$(CPP_SDK_VERSION)/lib/libopentelemetry_proto_grpc.a',
          '/usr/local/lib/libgrpc++.a',
          '/usr/local/lib/libgrpc.a',
          '/usr/local/lib/libgpr.a',
          '/usr/local/lib/libaddress_sorting.a',
          '-Wl,--allow-multiple-definition',
          '/usr/local/lib/libupb_base_lib.a',
          '/usr/local/lib/libupb_mem_lib.a',
          '/usr/local/lib/libupb_message_lib.a',
          '/usr/local/lib/libupb_mini_table_lib.a',
          '/usr/local/lib/libupb_mini_descriptor_lib.a',
          '/usr/local/lib/libupb_wire_lib.a',
          '/usr/local/lib/libupb_descriptor_lib.a',
          '/usr/local/lib/libupb_lex_lib.a',
          '/usr/local/lib/libupb_hash_lib.a',
          '/usr/local/lib/libupb_json_lib.a',
          '/usr/local/lib/libupb_textformat_lib.a',
          '/usr/local/lib/libupb_reflection_lib.a',
          '/usr/local/lib/libprotobuf.a',
          '/usr/local/lib/libupb.a',
          '/usr/local/lib/libutf8_range.a',
          '/usr/local/lib/libutf8_validity.a',
          '/usr/local/lib/libcares.a',
          '/usr/local/lib/libre2.a',
          '/usr/local/lib/libssl.a',
          '/usr/local/lib/libcrypto.a',
          '/usr/local/lib/libz.a',
          '/usr/local/lib/libabsl_base.a',
          '/usr/local/lib/libabsl_city.a',
          '/usr/local/lib/libabsl_civil_time.a',
          '/usr/local/lib/libabsl_cord.a',
          '/usr/local/lib/libabsl_cord_internal.a',
          '/usr/local/lib/libabsl_cordz_functions.a',
          '/usr/local/lib/libabsl_cordz_handle.a',
          '/usr/local/lib/libabsl_cordz_info.a',
          '/usr/local/lib/libabsl_cordz_sample_token.a',
          '/usr/local/lib/libabsl_crc32c.a',
          '/usr/local/lib/libabsl_crc_cord_state.a',
          '/usr/local/lib/libabsl_crc_cpu_detect.a',
          '/usr/local/lib/libabsl_crc_internal.a',
          '/usr/local/lib/libabsl_debugging_internal.a',
          '/usr/local/lib/libabsl_decode_rust_punycode.a',
          '/usr/local/lib/libabsl_demangle_internal.a',
          '/usr/local/lib/libabsl_demangle_rust.a',
          '/usr/local/lib/libabsl_die_if_null.a',
          '/usr/local/lib/libabsl_examine_stack.a',
          '/usr/local/lib/libabsl_exponential_biased.a',
          '/usr/local/lib/libabsl_failure_signal_handler.a',
          '/usr/local/lib/libabsl_flags_commandlineflag.a',
          '/usr/local/lib/libabsl_flags_commandlineflag_internal.a',
          '/usr/local/lib/libabsl_flags_config.a',
          '/usr/local/lib/libabsl_flags_internal.a',
          '/usr/local/lib/libabsl_flags_marshalling.a',
          '/usr/local/lib/libabsl_flags_parse.a',
          '/usr/local/lib/libabsl_flags_private_handle_accessor.a',
          '/usr/local/lib/libabsl_flags_program_name.a',
          '/usr/local/lib/libabsl_flags_reflection.a',
          '/usr/local/lib/libabsl_flags_usage.a',
          '/usr/local/lib/libabsl_flags_usage_internal.a',
          '/usr/local/lib/libabsl_graphcycles_internal.a',
          '/usr/local/lib/libabsl_hash.a',
          '/usr/local/lib/libabsl_hashtablez_sampler.a',
          '/usr/local/lib/libabsl_int128.a',
          '/usr/local/lib/libabsl_kernel_timeout_internal.a',
          '/usr/local/lib/libabsl_leak_check.a',
          '/usr/local/lib/libabsl_log_flags.a',
          '/usr/local/lib/libabsl_log_globals.a',
          '/usr/local/lib/libabsl_log_initialize.a',
          '/usr/local/lib/libabsl_log_internal_check_op.a',
          '/usr/local/lib/libabsl_log_internal_conditions.a',
          '/usr/local/lib/libabsl_log_internal_fnmatch.a',
          '/usr/local/lib/libabsl_log_internal_format.a',
          '/usr/local/lib/libabsl_log_internal_globals.a',
          '/usr/local/lib/libabsl_log_internal_log_sink_set.a',
          '/usr/local/lib/libabsl_log_internal_message.a',
          '/usr/local/lib/libabsl_log_internal_nullguard.a',
          '/usr/local/lib/libabsl_log_internal_proto.a',
          '/usr/local/lib/libabsl_log_internal_structured_proto.a',
          '/usr/local/lib/libabsl_log_severity.a',
          '/usr/local/lib/libabsl_log_sink.a',
          '/usr/local/lib/libabsl_low_level_hash.a',
          '/usr/local/lib/libabsl_malloc_internal.a',
          '/usr/local/lib/libabsl_periodic_sampler.a',
          '/usr/local/lib/libabsl_poison.a',
          '/usr/local/lib/libabsl_random_distributions.a',
          '/usr/local/lib/libabsl_random_internal_distribution_test_util.a',
          '/usr/local/lib/libabsl_random_internal_entropy_pool.a',
          '/usr/local/lib/libabsl_random_internal_platform.a',
          '/usr/local/lib/libabsl_random_internal_randen.a',
          '/usr/local/lib/libabsl_random_internal_randen_hwaes.a',
          '/usr/local/lib/libabsl_random_internal_randen_hwaes_impl.a',
          '/usr/local/lib/libabsl_random_internal_randen_slow.a',
          '/usr/local/lib/libabsl_random_internal_seed_material.a',
          '/usr/local/lib/libabsl_random_seed_gen_exception.a',
          '/usr/local/lib/libabsl_random_seed_sequences.a',
          '/usr/local/lib/libabsl_raw_hash_set.a',
          '/usr/local/lib/libabsl_raw_logging_internal.a',
          '/usr/local/lib/libabsl_scoped_set_env.a',
          '/usr/local/lib/libabsl_spinlock_wait.a',
          '/usr/local/lib/libabsl_stacktrace.a',
          '/usr/local/lib/libabsl_status.a',
          '/usr/local/lib/libabsl_statusor.a',
          '/usr/local/lib/libabsl_str_format_internal.a',
          '/usr/local/lib/libabsl_strerror.a',
          '/usr/local/lib/libabsl_string_view.a',
          '/usr/local/lib/libabsl_strings.a',
          '/usr/local/lib/libabsl_strings_internal.a',
          '/usr/local/lib/libabsl_symbolize.a',
          '/usr/local/lib/libabsl_synchronization.a',
          '/usr/local/lib/libabsl_throw_delegate.a',
          '/usr/local/lib/libabsl_time.a',
          '/usr/local/lib/libabsl_time_zone.a',
          '/usr/local/lib/libabsl_tracing_internal.a',
          '/usr/local/lib/libabsl_utf8_for_code_point.a',
          '/usr/local/lib/libabsl_vlog_config_internal.a',
          '-Wl,--end-group',
          '-lstdc++fs',
          '$(BOOST_LIB)',
          '$(LIBRARY_FLAGS)',
       ],
        'ldflags': [
        ],

     }],
    ],

  }]
}
