name: boost_log

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'instrumentation/boost_log/**'
      - '.github/workflows/boost_log.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'instrumentation/boost_log/**'
      - '.github/workflows/boost_log.yml'

permissions:
  contents: read

jobs:
  cmake_linux:
    name: CMake Linux
    runs-on: ubuntu-24.04
    steps:
      - name: checkout opentelemetry-cpp-contrib
        uses: actions/checkout@v7.0.1
      - name: setup dependencies
        working-directory: instrumentation/boost_log
        run: |
          sudo apt update -y
          xargs -a apt-packages.txt sudo apt install -y --no-install-recommends --no-install-suggests
      - name: build opentelemetry-cpp
        working-directory: instrumentation/boost_log
        run: |
          mkdir -p "build"
          cd "build"
          cmake .. \
            -G Ninja \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/sandbox" \
            -DBUILD_TESTING=ON \
            -DWITH_EXAMPLES=ON \
            -DOPENTELEMETRY_INSTALL=ON
          cmake --build . -j$(nproc)
          ctest -j1 --output-on-failure
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"
