# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: Fluentd exporter CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'exporters/fluentd/**'
      - '.github/workflows/fluentd.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'exporters/fluentd/**'
      - '.github/workflows/fluentd.yml'

permissions:
  contents: read

jobs:
  cmake_linux:
    name: CMake Linux
    runs-on: ubuntu-24.04
    steps:
      - name: checkout opentelemetry-cpp-contrib
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: setup dependencies
        working-directory: exporters/fluentd
        run: |
          sudo apt update -y
          xargs -a apt-packages.txt sudo apt install -y --no-install-recommends --no-install-suggests
      - name: build and test
        working-directory: exporters/fluentd
        run: |
          mkdir -p "build"
          cd "build"
          cmake .. \
            -G Ninja \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/sandbox" \
            -DBUILD_TESTING=ON \
            -DWITH_EXAMPLES=ON \
            -DOPENTELEMETRY_INSTALL=ON
          cmake --build . -j$(nproc)
          ctest -j1 --output-on-failure
