name: Geneva Metrics CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'exporters/geneva/**'
      - '.github/workflows/geneva_metrics.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'exporters/geneva/**'
      - '.github/workflows/geneva_metrics.yml'

permissions:
  contents: read

jobs:
  cmake_linux:
    name: CMake on Linux
    runs-on: ubuntu-24.04
    steps:
      - name: checkout otel contrib geneva metrics
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: setup
        working-directory: exporters/geneva
        run: |
          sudo apt update -y 
          xargs -a apt-packages.txt sudo apt install -y --no-install-recommends --no-install-suggests
      - name: run tests
        working-directory: exporters/geneva
        run: |
          mkdir -p "build"
          cd "build"
          cmake .. "-DCMAKE_PREFIX_PATH=$HOME/prebuilt-otel" \
            -DBUILD_TESTING=ON -DWITH_EXAMPLES=ON
          cmake --build . -j$(nproc)
          ctest
