name: glog

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'instrumentation/glog/**'
      - '.github/workflows/glog.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'instrumentation/glog/**'
      - '.github/workflows/glog.yml'

permissions:
  contents: read

jobs:
  cmake_linux:
    name: CMake Linux
    runs-on: ubuntu-24.04
    steps:
      - name: checkout glog
        uses: actions/checkout@v7.0.1
        with:
          repository: "google/glog"
          ref: "v0.7.0"
          path: "glog"
      - name: checkout opentelemetry-cpp-contrib
        uses: actions/checkout@v7.0.1
        with:
          path: opentelemetry-cpp-contrib
      - name: setup dependencies
        run: |
          sudo apt update -y
          sudo apt install -y --no-install-recommends --no-install-suggests \
            build-essential \
            cmake \
            ninja-build \
            libssl-dev \
            libcurl4-openssl-dev \
            libprotobuf-dev \
            protobuf-compiler \
            libgmock-dev \
            libgtest-dev \
            libbenchmark-dev
      - name: build glog
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/glog/build"
          cd "${GITHUB_WORKSPACE}/glog/build"
          cmake .. -G Ninja
          cmake --build . -j$(nproc)
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"
      - name: build and test instrumentation/glog
        working-directory: opentelemetry-cpp-contrib/instrumentation/glog
        run: |
          mkdir -p "build"
          cd "build"
          cmake .. \
            -G Ninja \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/sandbox" \
            -DBUILD_TESTING=ON \
            -DWITH_EXAMPLES=ON \
            -DOPENTELEMETRY_INSTALL=ON
          cmake --build . -j$(nproc)
          ctest -j1 --output-on-failure
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"
