name: glog

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'instrumentation/glog/**'
      - '.github/workflows/glog.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'instrumentation/glog/**'
      - '.github/workflows/glog.yml'

permissions:
  contents: read

jobs:
  cmake_linux:
    name: CMake Linux
    runs-on: ubuntu-24.04
    steps:
      - name: checkout glog
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: "google/glog"
          ref: "v0.7.0"
          path: "glog"
      - name: checkout opentelemetry-cpp-contrib
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          path: opentelemetry-cpp-contrib
      - name: checkout opentelemetry-cpp
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: "open-telemetry/opentelemetry-cpp"
          ref: "v1.19.0"
          path: "opentelemetry-cpp"
          submodules: "recursive"
      - name: setup dependencies
        working-directory: opentelemetry-cpp-contrib/instrumentation/glog
        run: |
          sudo apt update -y
          xargs -a apt-packages.txt sudo apt install -y --no-install-recommends --no-install-suggests
      - name: build glog
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/glog/build"
          cd "${GITHUB_WORKSPACE}/glog/build"
          cmake .. -G Ninja
          cmake --build . -j$(nproc)
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"
      - name: build opentelemetry-cpp
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/opentelemetry-cpp/build"
          cd "${GITHUB_WORKSPACE}/opentelemetry-cpp/build"
          cmake .. -G Ninja -DBUILD_TESTING=OFF -DWITH_BENCHMARK=OFF -DOPENTELEMETRY_INSTALL=ON
          cmake --build . -j$(nproc)
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"
      - name: build instrumentation/glog contrib
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/instrumentation-glog/build"
          cd "${GITHUB_WORKSPACE}/instrumentation-glog/build"
          cmake ../../opentelemetry-cpp-contrib/instrumentation/glog \
            -G Ninja \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/sandbox" \
            -DBUILD_TESTING=ON \
            -DWITH_EXAMPLES=ON \
            -DOPENTELEMETRY_INSTALL=ON
          cmake --build . -j$(nproc)
          ctest -j1 --output-on-failure
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"
