name: httpd instrumentation CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'instrumentation/httpd/**'
      - '.github/workflows/httpd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'instrumentation/httpd/**'
      - '.github/workflows/httpd.yml'

permissions:
  contents: read

jobs:
  build:
    name: Build module
    if: false  # disabled. TODO: fix this job
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup buildtools
        run: |
          sudo ./instrumentation/httpd/setup-buildtools.sh
          sudo ./instrumentation/httpd/setup-environment.sh
      - name: Compile
        run: |
          cd instrumentation/httpd && ./build.sh
          cp bazel-out/k8-opt/bin/otel.so /tmp/mod-otel.so
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.os }}_mod-otel.so
          path: /tmp/mod-otel.so

  build_cmake:
    name: Build module with CMake
    if: false  # disabled. TODO: fix this job
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup buildtools
        run: |
          sudo ./instrumentation/httpd/setup-buildtools.sh
          sudo ./instrumentation/httpd/setup-environment.sh
      - name: Compile prerequisites
        run: |
          cd instrumentation/httpd
          sudo ./setup-cmake.sh
      - name: Compile
        run: |
          cd instrumentation/httpd
          mkdir -p build
          cd build
          cmake ..
          make -j2

  e2e_tests:
    name: Run end-to-end tests
    if: false  # disabled. TODO: fix this job
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup buildtools
        run: |
          sudo ./instrumentation/httpd/tests/setup-tools.sh
          sudo ./instrumentation/httpd/setup-buildtools.sh
          sudo ./instrumentation/httpd/setup-environment.sh
      - name: Compile
        run: cd instrumentation/httpd && ./build.sh
      - name: Run tests
        run: |
          cd instrumentation/httpd && ./create-otel-load.sh
          sudo ./httpd_install_otel.sh
          cd tests && sudo ./run-all.sh
