name: log4cxx

on:
  push:
    branches:
      - '*'
    path:
      - 'instrumentation/log4cxx/**'
      - '.github/workflows/log4cxx.yml'
  pull_request:
    branches: [main]
    paths:
      - 'instrumentation/log4cxx/**'
      - '.github/workflows/log4cxx.yml'

permissions:
  contents: read

jobs:
  cmake_linux:
    name: CMake Linux
    runs-on: ubuntu-24.04
    steps:
      - name: checkout logging-log4cxx
        uses: actions/checkout@v7.0.1
        with:
          repository: "apache/logging-log4cxx"
          ref: "rel/v1.2.0"
          path: "logging-log4cxx"
      - name: checkout opentelemetry-cpp-contrib
        uses: actions/checkout@v7.0.1
        with:
          path: opentelemetry-cpp-contrib
      - name: setup dependencies
        run: |
          sudo apt update -y
          sudo apt install -y --no-install-recommends --no-install-suggests \
            build-essential \
            cmake \
            ninja-build \
            libssl-dev \
            libcurl4-openssl-dev \
            libprotobuf-dev \
            protobuf-compiler \
            libgmock-dev \
            libgtest-dev \
            libbenchmark-dev \
            liblog4cxx-dev

      # This is needed because liblog4cxx-dev installs 0.12.1-4,
      # and v1.0.0 is required
      - name: build logging-log4cxx
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/logging-log4cxx/build"
          cd "${GITHUB_WORKSPACE}/logging-log4cxx/build"
          cmake .. -G Ninja
          cmake --build . -j$(nproc)
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"
      - name: build and test instrumentation/log4cxx
        working-directory: opentelemetry-cpp-contrib/instrumentation/log4cxx
        run: |
          mkdir -p "build"
          cd "build"
          cmake .. \
            -G Ninja \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/sandbox" \
            -DBUILD_TESTING=ON \
            -DWITH_EXAMPLES=ON \
            -DOPENTELEMETRY_INSTALL=ON
          cmake --build . -j$(nproc)
          ctest -j1 --output-on-failure
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"

