name: spdlog

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'instrumentation/spdlog/**'
      - '.github/workflows/spdlog.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'instrumentation/spdlog/**'
      - '.github/workflows/spdlog.yml'

permissions:
  contents: read

jobs:
  cmake_linux:
    name: CMake Linux
    runs-on: ubuntu-24.04
    steps:
      - name: checkout opentelemetry-cpp-contrib
        uses: actions/checkout@v7.0.1
      - name: setup dependencies
        run: |
          sudo apt update -y
          sudo apt install -y --no-install-recommends --no-install-suggests \
            build-essential \
            cmake \
            ninja-build \
            libssl-dev \
            libcurl4-openssl-dev \
            libprotobuf-dev \
            protobuf-compiler \
            libgmock-dev \
            libgtest-dev \
            libbenchmark-dev \
            libspdlog-dev
      - name: build instrumentation/spdlog contrib
        working-directory: instrumentation/spdlog
        run: |
          mkdir -p "build"
          cd "build"
          cmake .. \
            -G Ninja \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/sandbox" \
            -DBUILD_TESTING=ON \
            -DWITH_EXAMPLES=ON \
            -DOPENTELEMETRY_INSTALL=ON
          cmake --build . -j$(nproc)
          ctest -j1 --output-on-failure
          cmake --install . --prefix="${GITHUB_WORKSPACE}/sandbox"
